name: Stable Builds
on:
  push:
    branches:
      - production
env:
  BUILD_TYPE: Release
jobs:
  prep:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
      - uses: actions/checkout@v2
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Cache Conan packages
        uses: actions/cache@v3
        id: cache-conan
        env:
          cache-name: cache-conan
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/conanfile.py') }}
          path: |
            ~/.conan/
      - if: ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
        name: Create default profile
        run: conan profile new default --detect
      - if: ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
        name: Update profile 11
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - if: ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
        name: Update profile version
        run: conan profile update settings.compiler.version=10 default
      - if: ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
        name: Add conan remote
        run: |
          conan config set general.revisions_enabled=True
          conan remote add proofofwork https://conan.pow.co/artifactory/api/conan/conan
    outputs:
      releaseVersion: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
  test:
    runs-on: ubuntu-latest
    needs:
      - prep
    steps:
      - uses: actions/checkout@v2
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Cache Conan packages
        uses: actions/cache@v3
        env:
          cache-name: cache-conan
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/conanfile.py') }}
          path: |
            ~/.conan/
      - name: run tests
        run: |
          mkdir test_build
          cd test_build
          conan install .. -r=proofofwork
          cmake .. -DPACKAGE_TESTS=ON
          cmake --build .
          cd bin
          for f in test*; do "./$f" ; done
  build:
    runs-on: ubuntu-latest
    needs:
      - prep
      - test
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: proofofwork/boostminer
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,${{ needs.prep.outputs.version }}
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Cache Conan packages
        uses: actions/cache@v3
        env:
          cache-name: cache-conan
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/conanfile.py') }}
          path: |
            ~/.conan/
      - name: prepare release package
        run: |
          mkdir build
          cd build
          conan install .. -r=proofofwork
          cmake .. -DPACKAGE_TESTS=Off
          cmake --build .
          export CURRENT_VERSION="${{ needs.prep.outputs.releaseVersion }}"
          tar -czvf "BoostMiner-${CURRENT_VERSION}-linux.tar.gz" bin/*
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ needs.prep.outputs.releaseVersion }}
          file: build/BoostMiner-${{ needs.prep.outputs.releaseVersion }}-linux.tar.gz
          asset_name: BoostMiner-${{ needs.prep.outputs.releaseVersion }}-linux.tar.gz